In [1]:
import torch

# 5.1 加减乘除 乘方开方 次方 log 

In [12]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[5,6],[7,8]])

print("-----  a+b: -----")
print(a+b)
print(torch.add(a,b))
print("-----  a-b: -----")
print(a-b)
print(torch.sub(a,b))
print("-----  a*b: -----")
print(a*b)
print(torch.mul(a,b))
print("-----  a/b: -----")
print(a/b)
print(torch.div(a,b))
print("-----  a^b: -----")
print(a**b)
print(torch.pow(a,b))
print("-----  long(a): -----")
print(torch.log(a))
print("-----  sqrt(a): -----")
print(torch.sqrt(a))


-----  a+b: -----
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])
-----  a-b: -----
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[-4., -4.],
        [-4., -4.]])
-----  a*b: -----
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[ 5., 12.],
        [21., 32.]])
-----  a/b: -----
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
-----  a^b: -----
tensor([[1.0000e+00, 6.4000e+01],
        [2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01],
        [2.1870e+03, 6.5536e+04]])
-----  long(a): -----
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
-----  rsquare(a): -----
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


# 5.2 矩阵相乘

In [34]:
A = torch.FloatTensor([[[1,2],[3,4]]])
B = torch.FloatTensor([[[5,6],[7,8]]])
print("-------A dot B------")
print(torch.matmul(A,B))
print(A@B)


-------A dot B------
tensor([[[19., 22.],
         [43., 50.]]])
tensor([[[19., 22.],
         [43., 50.]]])


# 5.3 取整，约等于，上下限制

In [30]:
a = torch.FloatTensor([[0.3, 0.4, 0.5, 0.6, 1, 1.4, 1.5, 1.7,2,2.1]])
print("a:")
print(a)
print("------  torch.ceil(a)  -------")
print(torch.ceil(a))
print("------  torch.floor(a)  -------")
print(torch.ceil(a))

print("------  torch.round(a)  -------")
print(torch.round(a))
print("------  torch.trunc(a)  -------")
print(torch.trunc(a))
print("------  torch.frac(a)  -------")
print(torch.frac(a))
print("------  torch.clamp(a,1,2)  -------")
print(torch.clamp(a,1,2))

a:
tensor([[0.3000, 0.4000, 0.5000, 0.6000, 1.0000, 1.4000, 1.5000, 1.7000, 2.0000,
         2.1000]])
------  torch.ceil(a)  -------
tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 3.]])
------  torch.floor(a)  -------
tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 3.]])
------  torch.round(a)  -------
tensor([[0., 0., 0., 1., 1., 1., 2., 2., 2., 2.]])
------  torch.trunc(a)  -------
tensor([[0., 0., 0., 0., 1., 1., 1., 1., 2., 2.]])
------  torch.frac(a)  -------
tensor([[0.3000, 0.4000, 0.5000, 0.6000, 0.0000, 0.4000, 0.5000, 0.7000, 0.0000,
         0.1000]])
------  torch.clamp(a,1,2)  -------
tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.4000, 1.5000, 1.7000, 2.0000,
         2.0000]])


# 5.4 统计函数

In [48]:
a = torch.FloatTensor([[1,2,3,4,5,6]])
print("------- tensor范数 torch.norm(a,2) ------")
print(torch.norm(a,2))
print("------- tensor最大值 ,最小值， ------")
print(torch.max(a))
print(torch.min(a))
print("------- tensor 均值,求和 ------")
print(a.mean())
print(torch.sum(a, dim=1))
print("------- tensor 最大值索引， 最小值索引 ------")
print(a.argmax())
print(torch.argmin(a))
print("------- tensor 最大K个值 ------")
print(a.topk(3))

------- tensor范数 torch.norm(a,2) ------
tensor(9.5394)
------- tensor最大值 ,最小值， ------
tensor(6.)
tensor(1.)
------- tensor 均值,求和 ------
tensor(3.5000)
tensor([21.])
------- tensor 最大值索引， 最小值索引 ------
tensor(5)
tensor(0)
------- tensor 最大K个值 ------
(tensor([[6., 5., 4.]]), tensor([[5, 4, 3]]))


## torch.where(condidtion, true_state, false_state)
## condidtion, true_state, false_state shape is the same shape

In [65]:
cond = torch.randn(2,2)
a = torch.ones(cond.shape) * 8
b = torch.ones(cond.shape) * 5
print("cond = ", cond)
torch.where(cond > 0,a,b)

cond =  tensor([[1.5433, 0.5111],
        [0.8630, 0.6903]])


tensor([[8., 8.],
        [8., 8.]])

## 收集器。 按index tensor对 通shape input tensor 收集样本

In [72]:
a = torch.Tensor([[1,2],[3,4]]) 
i = torch.tensor([[1,0],[0,1]])
torch.gather(a,dim=0,index = i)

tensor([[3., 2.],
        [1., 4.]])

In [77]:
torch.sigmoid(torch.Tensor([0.1,-2,2]))

tensor([0.5250, 0.1192, 0.8808])

# ----------------------------------------------------------------

In [82]:
a = torch.rand(3, requires_grad=True)
p = torch.softmax(a,dim=0)
torch.autograd.grad(p[1],[a], retain_graph=True)

(tensor([-0.1200,  0.2373, -0.1173]),)

In [85]:
torch.autograd.grad(p[1],[a], retain_graph=True)

(tensor([-0.1200,  0.2373, -0.1173]),)