In [1]:
import torch

# 5.1 加减乘除 乘方开方 次方 log 

In [12]:
a = torch.FloatTensor([[1,2],[3,4]])
b = torch.FloatTensor([[5,6],[7,8]])

print("-----  a+b: -----")
print(a+b)
print(torch.add(a,b))
print("-----  a-b: -----")
print(a-b)
print(torch.sub(a,b))
print("-----  a*b: -----")
print(a*b)
print(torch.mul(a,b))
print("-----  a/b: -----")
print(a/b)
print(torch.div(a,b))
print("-----  a^b: -----")
print(a**b)
print(torch.pow(a,b))
print("-----  long(a): -----")
print(torch.log(a))
print("-----  sqrt(a): -----")
print(torch.sqrt(a))


-----  a+b: -----
tensor([[ 6.,  8.],
        [10., 12.]])
tensor([[ 6.,  8.],
        [10., 12.]])
-----  a-b: -----
tensor([[-4., -4.],
        [-4., -4.]])
tensor([[-4., -4.],
        [-4., -4.]])
-----  a*b: -----
tensor([[ 5., 12.],
        [21., 32.]])
tensor([[ 5., 12.],
        [21., 32.]])
-----  a/b: -----
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
-----  a^b: -----
tensor([[1.0000e+00, 6.4000e+01],
        [2.1870e+03, 6.5536e+04]])
tensor([[1.0000e+00, 6.4000e+01],
        [2.1870e+03, 6.5536e+04]])
-----  long(a): -----
tensor([[0.0000, 0.6931],
        [1.0986, 1.3863]])
-----  rsquare(a): -----
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


# 5.2 矩阵相乘

In [16]:
A = torch.FloatTensor([[1,2],[3,4]])
B = torch.FloatTensor([[5,6],[7,8]])
print("-------A dot B------")
print(torch.mm(A,B))
print(A@B)

-------A dot B------
tensor([[19., 22.],
        [43., 50.]])
tensor([[19., 22.],
        [43., 50.]])


# 5.3 取整，约等于，上下限制

# 5.4 统计函数