In [32]:
import torch
import torch.nn.functional as F

In [33]:
x = torch.ones(1)
#requires_grad=True 标准对该变量求导
w = torch.full([1],2, requires_grad=True)

In [34]:
x

tensor([1.])

In [35]:
w

tensor([2.], requires_grad=True)

## 如果第二次执行， 报错。  因为每一次计算梯度后，动态图需要重构

In [39]:
#对指定参数列表求导
torch.autograd.grad(mse, [w])

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [40]:
mse = F.mse_loss(torch.ones(1), x*w)
mse.backward() # 对所有的的参数求导， 并且保存到参数.grad

In [41]:
w.grad

tensor([2.])

In [53]:
t = torch.tensor([1.,2.,3.,4.], requires_grad=True)

In [55]:
torch.softmax(t, dim=0)[0].backward()
t.grad

tensor([ 0.0310, -0.0028, -0.0076, -0.0206])