# Numpy 35 个实战

为了训练自己数量使用numpy， 根据知乎帖Numpy35个实战，编写一本笔记用于记忆和教育的材料。

参考材料： https://zhuanlan.zhihu.com/p/36303821?utm_source=wechat_session&utm_medium=social&utm_oi=30635422908416

## 挑战 1：引入 numpy 并查看 numpy 的版本。

要求：这是第一步，以后我们使用 numpy 时都将用别名 np。

In [4]:
import numpy as np
print(np.__version__)

1.14.5


## 挑战2： 创建数组

创建一组数组， 从0到9

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 挑战3：创建布尔数组 

要求：数组大小为 3*3，全部为 True。

In [6]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
np.ones([3,3], dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 挑战 4：按要求抽取数组中的元素

要求：原数组为一维数组，内容为从 0 到 9，抽取出所有奇数。

In [10]:
arr = np.arange(0,10)
arr[1::2]

array([1, 3, 5, 7, 9])

## 挑战 5：按要求修改数组中的元素（原地修改）

要求：原数组为一维数组，内容为从 0 到 9，将所有奇数原地修改为 -1。

In [13]:
arr = np.arange(0,9)
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

## 挑战 6：按要求修改数组中的元素（返回新数组）

要求：原数组为一维数组，内容为从 0 到 9，返回一个该数组的拷贝，其中奇数修改为 -1。

In [18]:
arr = np.arange(0,9)
np.where(arr%2==1, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

## 挑战 7：修改数组的形状

要求：将给定的一维数组 reshape 为二维数组，其中新数组的行数为2。

In [20]:
arr = np.array([1,2,3,4,5,6])
arr.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

## 挑战 8：合并数组（列方向）

要求：将给定数组在列方向上合并。

In [25]:
arr_1 = np.arange(10).reshape(2,5)
arr_2 = np.arange(10,20).reshape(2,5)
np.concatenate([arr_1, arr_2], axis=0)   # 这个API不是很熟悉， 需要多看看。 站在API设计者的角度去考虑问题

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [27]:
np.vstack([arr_1,arr_2])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
np.r_[arr_1,arr_2]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 挑战 9：合并数组（水平方向）

要求：将给定数组在水平方向上合并。

In [26]:
arr_1 = np.arange(10).reshape(2,5)
arr_2 = np.arange(10,20).reshape(2,5)
np.concatenate([arr_1, arr_2], axis=1)   # 这个API不是很熟悉， 需要多看看。 站在API设计者的角度去考虑问题

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [28]:
np.hstack([arr_1, arr_2])

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [31]:
np.c_[arr_1, arr_2]

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

## 挑战 10：创建数组（进阶）

要求：不用硬编码，使用内置方法，从给定数组 a 生成数组 b。